### ISSUE TITLE
Some ambiguities in coursework 1

### ISSUE THREAD

**Issue by kgilden** [juhan/itt8060#1]
Hi,

I'm having a hard time understanding exactly what's being asked in coursework 1.

In [point 6](https://github.com/juhan/itt8060/blob/master/coursework1.fsx#L37)

> elements in tuples containing 2, 3, or four elements of float type

Will all the input tuples contain the same number of elements and then of those elements either 2, 3 or 4 are floats? Should the function accept a tuple of 5 (or more) elements? It would be great to have some example inputs.

In [point 7](https://github.com/juhan/itt8060/blob/master/coursework1.fsx#L40)

> capitalizes the names strings in a tuple of strings of size 2,3, or 4

Does it mean the tuple can have either 2, 3 or 4 elements or that all elements in the tuple are strings and each such string can be of length 2, 3 or 4? Again, some example inputs and examples would be nice.

Thanks,
Kristen

**Comment by juhan** [comment]
Hi! Thanks for pointing out the ambiguities. Improved wording is used in in https://github.com/juhan/itt8060/commit/755dbd84fb4d8b0ecbbc144d4fb409a5c1cd5218.
